### PR TITLE
Refactor SQS creds provider

### PR DESCRIPTION
**Pull request by abhide**
Tickets: https://github.com/vinyldns/vinyldns/issues/1008
Fixes: #1008 

Changes in this pull request:
-
-

### CODE REVIEW

**Review by pauljamescleary — APPROVED** [review]

**Comment by pauljamescleary** [comment]
@abhide this is failing because...

```
Expected exception pureconfig.error.ConfigReaderException to be thrown, but com.amazonaws.SdkClientException was thrown (SqsMessageQueueProviderIntegrationSpec.scala:48)
```

Unclear on why exactly.

To test / fix this locally:

1. start up `sbt`
2. type `project root`
3. type `dockerComposeRestart`
4. type `project sqs`
5. type `it:test`

**Comment by pauljamescleary** [comment]
@abhide I am looking at what is happening in the build.  This is now happening alot.  Some kind of config file loading on the `Build and Test` job.

**Comment by abhide** [comment]
> @abhide this is failing because...
> 
> ```
> Expected exception pureconfig.error.ConfigReaderException to be thrown, but com.amazonaws.SdkClientException was thrown (SqsMessageQueueProviderIntegrationSpec.scala:48)
> ```
> 
> Unclear on why exactly.
> 
> To test / fix this locally:
> 
> 1. start up `sbt`
> 2. type `project root`
> 3. type `dockerComposeRestart`
> 4. type `project sqs`
> 5. type `it:test`

@pauljamescleary I will look into this.

**Comment by abhide** [comment]
@pauljamescleary figured out the issue. If `secret-key` and `access-key` aren't specified then the AWSDefaultCredentialsChain will be picked up. The integration was testing bad config by omitting one of those; and was failing as expected. So I fixed the test to omit `signing-region` to keep the valid and fail as expected as before.

I will add more integration for the changes I made in another PR.

**Comment by pauljamescleary** [comment]
Thanks!

**Pull request merged**
