### PR TITLE
collapse fix in manage records

### LINKED ISSUE #1297: Portal UI Fixes- Collapse the Recent Record Changes is not working in zone page.
Bug:-
Collapse the Recent Record Changes is not working in `manage records `tab inside zone view. 

Follow up with #1295

image

### PR DESCRIPTION
**Pull request by Jay07GIT**
Fixes #1297.

Changes in this pull request:
- collapse fix for manage records in zones view page.

### CODE REVIEW

**Review by Aravindh-Raju — APPROVED** [review]
Tested locally. Looks good to me!

**Review by arpit4ever — APPROVED** [review]
LGTM

**Review by nspadaccino — COMMENTED** [review]
Functionality looks good, but when I hover my cursor over the collapse button, it doesn't give any indication that it is clickable. Is that possible to add?

**Comment by Jay07GIT** [comment]
> Functionality looks good, but when I hover my cursor over the collapse button, it doesn't give any indication that it is clickable. Is that possible to add?

Sure. I added the mouse over for the indication.

**Review by arpit4ever — APPROVED** [review]
LGTM

**Review by nspadaccino — APPROVED** [review]

**Pull request merged**
