### PR TITLE
Add pagination in group view

### LINKED ISSUE #1137: Add Pagination in Groups view
Currently we don’t have pagination in `Groups` view. We only have infinite scroll. 
Add pagination in `Groups` view similar to what we have in `Zones` view.

### PR DESCRIPTION
**Pull request by Aravindh-Raju**
Fixes #1137.

Changes in this pull request:
- Added pagination in `Groups` view similar to what we have in `Zones` view.

### CODE REVIEW

**Review by nspadaccino — DISMISSED** [review]
Tested locally with a connection to the actual database so I could page through all the groups, looks good

**Review by Jay07GIT — APPROVED** [review]
LGTM. Can be merge.

**Review by nspadaccino — COMMENTED** [review]
I tested this again locally with a database snapshot so I could look at all of our groups, and I noticed that the groups are not in overall alphabetical order across the pages. Within one page the groups are alphabetized, but the selection of groups that are displayed on the page seems random. I expected page 1 to have groups starting with symbols or the letter "A", but instead I'm getting groups from all over the alphabet. Could you check the behavior on your side?

**Comment by Aravindh-Raju** [comment]
> I tested this again locally with a database snapshot so I could look at all of our groups, and I noticed that the groups are not in overall alphabetical order across the pages. Within one page the groups are alphabetized, but the selection of groups that are displayed on the page seems random. I expected page 1 to have groups starting with symbols or the letter "A", but instead I'm getting groups from all over the alphabet. Could you check the behavior on your side?

Thanks for finding that out. I've made the changes to sort groups by `name` instead of `id`. It should be working fine as expected now. Please have a look.

**Review by nspadaccino — APPROVED** [review]
Looks good to me

**Pull request merged**
