### PR TITLE
multi-record support for txt in portal and batch

### LINKED ISSUE #547: Multi-record support for TXT records
**Describe the bug**
Presently, VinylDNS does not support multiple records for TXT records **in the UI**.  It is supported everywhere else in the system

**VinylDNS Version**
Latest

**Expected behavior**
Support a multi-record record set for TXT record types. 

Should be supported in the UI and the API

Should support large TXT rdata, as it can be 65000 characters

### PR DESCRIPTION
**Pull request by britneywright**
Fixes #547.

Changes in this pull request:
- allow input of multi-record TXT record sets in the portal
- display multi-record TXT record sets in the portal
- change the "more..." and "less.." links in multi-record record sets from list level items to span and rename as "Show more..." and "Show fewer..."

Screen Shot 2019-03-29 at 2 25 01 PM

Screen Shot 2019-03-29 at 2 23 54 PM

Screen Shot 2019-03-29 at 2 24 06 PM

API:

- allow multiple TXT records with the same record name in batch changes

### CODE REVIEW

**Comment by pauljamescleary** [comment]
@britneywright thanks for the screen shots.  Is the multi-record TEXT just separated by newline in the same text area?

I think we may need to review the design.  Each TXT record in a record set has the potential to be very large (65,000 characters).

**Comment by britneywright** [comment]
> @britneywright thanks for the screen shots. Is the multi-record TEXT just separated by newline in the same text area?
> 
> I think we may need to review the design. Each TXT record in a record set has the potential to be very large (65,000 characters).

Correct, they're separated by new lines. I can test long record data and see how they work.

**Comment by britneywright** [comment]
Realized we weren't allowing TXT records with the same input name in batch changes on the API side, updated that as well.

**Comment by britneywright** [comment]
> Confirmed that this works with #568, but concerned that we're not wrapping the columns which stretches the layout.

That's a separate issue https://github.com/vinyldns/vinyldns/issues/477

**Pull request merged**
