### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by palash25**
Edit step 4 under Quickstart section to use the
correct shell command to run the docker-compose script.

Fixes #.

Changes in this pull request:
- Minor doc fix

### CODE REVIEW

**Comment by palash25** [comment]
I don't really understand the webpage that the CLA assistant provides here, it shows me a blank page with version written on it and no option to sign the CLA. No clickable elements on that page. Please let me know how I can sign the CLA. :smile:

**Comment by britneywright** [comment]
HI @palash25 thank you for the contribution, If you'd like you can make another commit to add your name to our Authors list: https://github.com/vinyldns/vinyldns/blob/master/AUTHORS.md list

**Comment by palash25** [comment]
done @britneywright

**Comment by britneywright** [comment]
and don't forget to sign the CLA please

**Comment by palash25** [comment]
signed

**Pull request merged**
