### PR TITLE
update scala

### LINKED ISSUE #251: Upgrade to scala 2.12.7
**Motivation**
Stay current with latest, supposedly a bump in compiler performance

**Scope of change**
Change build.sbt, and the scala version in it

### PR DESCRIPTION
**Pull request by davidmargolin**
Updates scala to 2.12.7
resolves #251

### CODE REVIEW

**Comment by pauljamescleary** [comment]
Thanks @davidmargolin!!  Also, feel free to add yourself to our `AUTHORS.md` if you feel so inclined.

Letting travis to its thing :)

**Comment by davidmargolin** [comment]
looks like more than i thought... switching to WIP

**Comment by pauljamescleary** [comment]
@davidmargolin we haven't linked to profiles yet.  If you add yourself to AUTHORS, you can do a link to your github profile if you wish.  I may add mine as well.  It really is an individual choice.

**Comment by pauljamescleary** [comment]
Interesting on the build failure, one of them succeeded and the other failed?  I may just rebuild that one, perhaps some travis cache woes?

**Comment by nimaeskandary** [comment]
May even need to clear out the travis caches on a scala update, unsure

**Comment by rebstar6** [comment]
@davidmargolin try updating the version in .travis.yml too

**Comment by pauljamescleary** [comment]
It _maybe_ possible also that the new scala version is finding a few unused things in our code

* MembershipRoute - line 96 - `path("groups" / Segment) { id =>`, id is not used, can change this to `_`
* RecordSetRoute - line 107 `(zoneId, rsId, changeId) =>` the `rsId` is not used, this can change to `_`
* VinylDNSDirectives - line 39 - I don't think we need the extractExecutionContext any more, so that can be deleted
* ZoneRoute -  line 79 - `(put & path("zones" / Segment) & monitor("Endpoint.updateZone")) { id =>`, the `id` at the end there is not used, can be changed to `_`

**Build Output**

```
[error] /home/travis/build/vinyldns/vinyldns/modules/api/src/main/scala/vinyldns/api/route/MembershipRouting.scala:96:34: parameter value id in value $anonfun is never used
[error]       path("groups" / Segment) { id =>
[error]                                  ^
[error] /home/travis/build/vinyldns/vinyldns/modules/api/src/main/scala/vinyldns/api/route/RecordSetRouting.scala:107:18: parameter value rsId in value $anonfun is never used
[error]         (zoneId, rsId, changeId) =>
[error]                  ^
[error] /home/travis/build/vinyldns/vinyldns/modules/api/src/main/scala/vinyldns/api/route/VinylDNSDirectives.scala:39:48: parameter value ec in value $anonfun is never used
[error]     extractExecutionContext.flatMap { implicit ec ⇒
[error]                                                ^
[error] /home/travis/build/vinyldns/vinyldns/modules/api/src/main/scala/vinyldns/api/route/ZoneRouting.scala:79:74: parameter value id in value $anonfun is never used
[error]       (put & path("zones" / Segment) & monitor("Endpoint.updateZone")) { id =>
[error]                                                                          ^
[error] four errors found
```

**Comment by pauljamescleary** [comment]
Confirmed, same thing happens locally.  The adjustments I mentioned above worked.  

@davidmargolin willing to make those changes ⬆️ in my last comment and post an update to the PR.  No unit tests or anything else need to be made.  Let me know if you have any questions.

**Comment by pauljamescleary** [comment]
I fixed the initial ones locally, and there are _sooo_ many more.  Apologies @davidmargolin thought this would be simpler.  Squashing the compiler warnings is annoying

**Comment by davidmargolin** [comment]
finally haha. Thanks for the opportunity and the help

**Pull request merged**
