### PR TITLE
Updates to zone sync scheduler

### PR DESCRIPTION
**Pull request by Aravindh-Raju**
Changes in this pull request:
- Minor updates to zone sync scheduler: Added 24hr format to time picker. Added minutes to increment by 5. Added trailing zero before minute values in scheduler dropdown. Hidden calendar as it is not necessary. Removed unnecessary logs.

### CODE REVIEW

**Review by nspadaccino — COMMENTED** [review]
One suggested change:
The UTC time converter has you enter the local time in 24 hour format, but returns the UTC time in 12 hour format, which you then have to convert back to 24 hour format to put into the scheduler. Could we just return the UTC time in 24 hour format instead? That way everything related to the scheduler will be in 24 hour format to reduce confusion

**Comment by Aravindh-Raju** [comment]
> One suggested change: The UTC time converter has you enter the local time in 24 hour format, but returns the UTC time in 12 hour format, which you then have to convert back to 24 hour format to put into the scheduler. Could we just return the UTC time in 24 hour format instead? That way everything related to the scheduler will be in 24 hour format to reduce confusion

Yes, that would make it a lot easier. Made the change.

**Review by nspadaccino — APPROVED** [review]
Looks good to me!

**Review by arpit4ever — APPROVED** [review]
LGTM

**Pull request merged**
