### PR TITLE
Resolve bug in group details update

### LINKED ISSUE #1161: Updating a group email removed all other members of the group
A user asked for the email of their group to be updated. I, as a superuser, tried to update the email (without being a member of the group) and got an error stating "Group must have at least one member and one admin". I don't think superusers can update a group they aren't part of, so this should have been a "Not Authorized" error, since the group clearly had more than one member and admin. 

After this, I added myself to the group as an admin, and updated the email. For some reason this update removed all other members of the group besides myself. I then had to manually add back all the members that had been removed.

We need to determine why this occurred to ensure it doesn't happen again with a larger group, which would cause a lot more problems.

Steps to recreate:
• Be added to an existing group as an admin
• Click the Edit button on the group in the group search view
• Edit the email and click Update

### PR DESCRIPTION
**Pull request by Aravindh-Raju**
Fixes #1161.

Changes in this pull request:
- Fixed a bug for group details update. A super user can now edit group details (name, email and description) without being part of the group and without removing existing members of the group.

### CODE REVIEW

**Review by nspadaccino — APPROVED** [review]
Looks good! Verified locally, nice job on finding a solution

**Comment by nspadaccino** [comment]
This doesn't seem to be working for me anymore in my local environment, when I try to update a group email it's still removing the other group members. @JoshSEdwards @Aravindh-Raju @Jay07GIT could you guys try it out and see if it works for you?

**Comment by JoshSEdwards** [comment]
> This doesn't seem to be working for me anymore in my local environment, when I try to update a group email it's still removing the other group members. @JoshSEdwards @Aravindh-Raju @Jay07GIT could you guys try it out and see if it works for you?

I also just tried it out locally and it seemed to work fine. See the screenshots, after email update, the group members are the same.

image

image

**Comment by nspadaccino** [comment]
> This doesn't seem to be working for me anymore in my local environment, when I try to update a group email it's still removing the other group members. @JoshSEdwards @Aravindh-Raju @Jay07GIT could you guys try it out and see if it works for you?

I found out there was an NPM error causing issues with my local environment, with that resolved the change works as expected.

**Review by nspadaccino — APPROVED** [review]

**Review by JoshSEdwards — APPROVED** [review]

**Pull request merged**
