### PR TITLE
Adding NAPTR support

### PR DESCRIPTION
**Pull request by tpretz**
Addition of support for the NAPTR RR Type

Clone of SRV support behaviour, adjusting as needed.

Room to improve validation, beyond my immediate abilities as a non-scala developer.

### CODE REVIEW

**Comment by nimaeskandary** [comment]
Thanks @tpretz! Did a quick glance so far and this is pretty sweet! Leaving a reminder for someone to make an issue to add NAPTR Batch Change Support when this is merged

**Comment by pauljamescleary** [comment]
Thanks @tpretz for the PR.  This is really good stuff :) .

**Comment by pauljamescleary** [comment]
A few comments:

1. Should add a functional test (add a python test under `modules/api/functional_test` in the `create_recordset_test.py`.  I asked @nimaeskandary to help out with that
2. We need to add cards to our backlog to update the different client libraries for support.  Those should all be pretty small

@tpretz do you use the client libraries at all, or only the web portal?

**Comment by tpretz** [comment]
My initial usecase, that drove this addition, is just via the portal.
(essentially self-service for a mobile team to drive their telco infra zones which use NAPTR heavily)

So, i don't have any other pull requests pending right now.
(although, the GUI modals are a bit cramped with the amount of fields NAPTRs require, didn't want to adjust that in this PR tho as its a bit out of scope for this RR addition)

My only other deviation is to disable the dotted hosts check (i know its generally good practice to avoid these, but with some of these infrastructure zones its not really practical to delegate at every ".")
I can see a proper solution is already raised for this in #521 
Being able to opt a zone out of these checks is going to be essential to on-board telco zones, or legacy zones prior to a cleanup. 

Anyway, thanks for making this project opensource, it's been very useful and i hope to expand my deployment to other usecases soon.

**Comment by pauljamescleary** [comment]
@tpretz Would you have time to meet up so we can discuss your use case / deployment?  Would love to get feedback to help us drive our backlog

**Comment by rebstar6** [comment]
Also, feel free to add yourself to https://github.com/vinyldns/vinyldns/blob/master/AUTHORS.md in this PR if you'd like!

**Comment by nimaeskandary** [comment]
@tpretz made a pr against yours with a couple func tests https://github.com/tpretz/vinyldns/pull/1

**Comment by nimaeskandary** [comment]
Screen Shot 2019-04-24 at 10 28 32 AM

made a couple records in the portal as well

**Pull request merged**
