### PR TITLE
[WIP] portal: sort columns in records table

### LINKED ISSUE #541: Add Sort feature in Record Table columns
**Is your feature request related to a problem? Please describe.**
I'm unable to sort columns in a zone's Records table. All entries get sorted by the their name, by default.

**Describe the solution you'd like**
Add a sort feature to each column in the table

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by britneywright**
Fixes #541.

Changes in this pull request:
- adds sorting to Name, Type and TTL columns fo the records table in the portal

order by name:
Screen Shot 2019-04-01 at 12 51 24 PM

order by name, reverse: 
Screen Shot 2019-04-01 at 12 51 33 PM

### CODE REVIEW

**Comment by pauljamescleary** [comment]
@britneywright this is portal only, right?  We would need to add sorting to the API as well

**Comment by mitruly** [comment]
To @pauljamescleary's point on needing the API to handle sorting, when reducing the record paging parameter (eg. `var recordsPaging = pagingService.getNewPagingParams(2);`) in `controller.records.js`, the sorting only affects the records that get returned by the API for that particular page.

**Comment by britneywright** [comment]
ah yeah forgot about the api pagination 🤦🏽‍♀️

**Comment by britneywright** [comment]
Closing for now, need to work on the API side

**Pull request closed without merging**
