### PR TITLE
Add a filter for Route53 API results

### LINKED ISSUE #1236: Fail to create a new record with Route53 backend
Route53 fails to create new records when there is a record with a name greater than the new record.

https://github.com/vinyldns/vinyldns/blob/874bd11e47ea891bd9f0487f955f3342813f2624/modules/r53/src/main/scala/vinyldns/route53/backend/Route53Backend.scala#L115-L118
When calling `ListResourceRecordSetsRequest`, `withStartRecordName` is set to the fqdn of the new name which is the right thing to do, but as per AWS docs (https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/route53/model/ListResourceRecordSetsRequest.html#withStartRecordName-java.lang.String-) when no match is found AWS will return all records that have a greater name than the requested value. 

The fix is something on the line of verifying the returned records and check if any does really match the requested name, if not return an empty list.

Some example for reproducing the error: 
1. We created a CNAME record `prometheus-shard-9-olx-prod-cops-1.sec.preprod.olxbr.io.` pointing to anywhere.
2. Try to create a record `faa.sec.preprod.olxbr.io`, fails with message `"Incompatible record in DNS."`
3. Manually query route53, replicating the code from Route53Backend:
```
import boto3

session = boto3.Session(profile_name='profile')
client = session.client('route53')
response = client.list_resource_record_sets(
    HostedZoneId='ZONE_ID',
    StartRecordName='faa.sec.preprod.olxbr.io.',
    StartRecordType='CNAME',
)

print(response)
```
Returns
```json
{
  "ResponseMetadata": {
    "RequestId": "bc44a86a-fa62-44f2-9418-83f6109aea34", 
    "HTTPStatusCode": 200, 
    "HTTPHeaders": {
      "x-amzn-requestid": "bc44a86a-fa62-44f2-9418-83f6109aea34", 
      "content-type": "text/xml", 
      "content-length": "477", "date": "Fri, 17 Mar 2023 18:25:37 GMT"
    }, 
    "RetryAttempts": 0
  }, 
  "ResourceRecordSets": [
    {
      "Name": "prometheus-shard-9-olx-prod-cops-1.sec.preprod.olxbr.io.", 
      "Type": "CNAME", 
      "TTL": 7200, 
      "ResourceRecords": [{"Value": "somewhere.com."}]
    }
  ], 
  "IsTruncated": False, 
  "MaxItems": "100"
}
```

Seems to affect all versions of the route53 backend.

### PR DESCRIPTION
**Pull request by pedrokiefer**
Route53 API can return larger names than requested when there is no exact match. This PR adds a filter ensuring that `resolve` method only returns a list when there is an exact match with the requested name and entry type.

I tried to reproduce the problem with tests, but the mocked Route53 does not return larger names. 

This PR has been applied to our internal deployment and is working as expected. There are more information on how to reproduce the error on the bug report #1236.

Fixes #1236.

### CODE REVIEW

**Review by Aravindh-Raju — APPROVED** [review]
Tested it out locally. Looks good to me!

**Review by JoshSEdwards — APPROVED** [review]
Tested locally - LGTM

**Review by nspadaccino — DISMISSED** [review]

**Review by JoshSEdwards — APPROVED** [review]

**Comment by nspadaccino** [comment]
Hey @pedrokiefer, we require all commits to be signed before merging a PR, and it looks like your first commit for this branch isn't signed. Could you open a duplicate PR and sign all the commits? You could also try some git wizardry to retroactively sign the commit for this PR, but it will probably be more of a hassle than opening a new PR.

**Comment by arpit4ever** [comment]
Hey @pedrokiefer, moving current PR to v0.19.1 milestone. Once we have a new PR (or updated commit), we will merge the changes.

**Comment by pedrokiefer** [comment]
I’ll update the PR later tonight.

**Comment by arpit4ever** [comment]
Hey @pedrokiefer, we have moved current PR to v0.19.2 milestone. Once we have a new PR (or updated commit), we will merge the changes.

**Comment by pedrokiefer** [comment]
Sorry for the delay, just signed the commit.

**Review by nspadaccino — APPROVED** [review]
Looks good to me!

**Pull request merged**
