### PR TITLE
Rename batch change files to dns change

### LINKED ISSUE #847: Rename "batch change" files to "dns change"
We have recently renamed our "batch change" to "DNS Change" in the portal UI. To be consistent, we should also rename the Javascript and HTML files.

-----
Good candidate files for changes:
- `/modules/portal/public/lib/batch-change` directory and included files
- `/modules/portal/app/views/batchChanges` directory and included files

### PR DESCRIPTION
**Pull request by ericcheatham**
Fixes #847 .

Changes in this pull request:
- Rename files in `modules/portal/app/views/{batchChanges}/*` -> `modules/portal/app/views/{dnsChanges}/*`
- Rename files in `modules/portal/public/lib/{batch-change}/*` -> `modules/portal/public/lib/{dns-change}/*`
- Update relevant uses and references

### CODE REVIEW

**Comment by pauljamescleary** [comment]
@ericcheatham Nice!  Just need to verify there are no missing files / endpoints / methods / functions in the portal.  Thanks!

**Comment by mitruly** [comment]
@ericcheatham tested this locally and think these changes are good. Can you just remove the frontend page routes from our `modules/portal/conf/routes` file for batch changes:
```
GET           /batchchanges                      @controllers.FrontendController.viewAllBatchChanges
GET           /batchchanges/new                  @controllers.FrontendController.viewNewBatchChange
GET           /batchchanges/:id                  @controllers.FrontendController.viewBatchChange(id: String)
```

**Comment by ericcheatham** [comment]
@mitruly On it!

**Comment by mitruly** [comment]
@ericcheatham we will get the Java issue sorted out today and let you know when you can rebase; it seems that we need to move over to openjdk8 from oraclejdk8.

**Comment by ericcheatham** [comment]
@mitruly any word on this? Is changing over to openjdk8 something I can help with somehow?

**Comment by britneywright** [comment]
@ericcheatham rebase your PR against master now and it should run in travis. we changed the jdk in another PR that is now in master.

**Pull request merged**
