### PR TITLE
Add zone autocomplete search

### LINKED ISSUE #1188: Add Autocomplete feature in zone search
Add autocomplete feature in zone search to give matches from the database as we type.

### PR DESCRIPTION
**Pull request by Aravindh-Raju**
Fixes #1188.

Changes in this pull request:
- Added autocomplete feature in zone search. Now we get zone suggestions as we type along with text-highlight.

### CODE REVIEW

**Review by nspadaccino — DISMISSED** [review]
Looks good! Tested in chrome, firefox, and safari

**Review by Jay07GIT — APPROVED** [review]
Looks good to me.

**Review by JoshSEdwards — DISMISSED** [review]
LGTM! Verified it locally

**Comment by JoshSEdwards** [comment]
Tested admin group search autocomplete and it looked good 👍

**Review by JoshSEdwards — APPROVED** [review]

**Review by nspadaccino — APPROVED** [review]
LGTM

**Pull request merged**
