### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by britneywright**
Changes in this pull request:

- Add a pull request template

### CODE REVIEW

**Comment by britneywright** [comment]
It's so much though 😩. maybe we should simplify that. Why do we need to list impacted files if you can see that in the PR.

**Comment by rebstar6** [comment]
yeah, i think anything we put in here we're gonna have to be pretty good about actually doing ourselves...the less overhead the better i think

**Comment by britneywright** [comment]
my main goal is to get us back in the habit of referencing the issue primarily and putting in some type of description. The template is intended as more of a reminder than a strict set of requirements.

**Comment by pauljamescleary** [comment]
I like it @britneywright

**Comment by pauljamescleary** [comment]
Am I the only one who uses `*` instead of `-` for bulleted lists?  Curious.

**Comment by britneywright** [comment]
yes 😁 
just kidding, but I definitely use `-` instead `*`

**Pull request merged**
