### PR TITLE
Fix for dns edit page after submit

### PR DESCRIPTION
**Pull request by Jay07GIT**
Fix
- Fix for dns edit page after submit.

Issue 
Spinner/ loader not closed properly when gets response

### CODE REVIEW

**Review by Aravindh-Raju — COMMENTED** [review]
I still see the issue when tested locally.

**Review by Aravindh-Raju — APPROVED** [review]
LGTM!

**Review by arpit4ever — APPROVED** [review]
LGTM
Tested locally.

**Review by JoshSEdwards — APPROVED** [review]
LGTM

**Pull request merged**
