### PR TITLE
Add JDK 11 support

### LINKED ISSUE #271: Consider JDK9+ support
**Motivation**

[The public update of Oracle JDK 8 will ends in January 2019](https://www.oracle.com/technetwork/java/javase/eol-135779.html).

To keep maintaining, vinyldns should support JDK 11 because it has Long Term Support.

* Oracle announcd [OpenJDK 11 has LTS](https://blogs.oracle.com/java-platform-group/update-and-faq-on-the-java-se-release-cadence)
* AdoptOpenJDK, sponsored by non-Oracle vendors and communities, also announced [support](https://adoptopenjdk.net/support.html)

**Scope of change**
* Add `openjdk11` in Travis CI's build matrix so that we can test on JDK 11
* Add some dependencies that had been removed from JDK since JDK 9+

### PR DESCRIPTION
**Pull request by exoego**
Fixes #271.

Changes in this pull request:
- Adds `openjdk11` in Travis build matrix.
- Rewrites the deprecated `klass.newInstance()` with `klass.getDeclaredConstructor().newInstance()`
- Adds the `jaxb` dependencies which had been removed from JDK since JDK 9.
- Updates `aws-sdk` and `sbt-assembly` to support JDK 11.

### CODE REVIEW

**Comment by exoego** [comment]
@pauljamescleary 
Because Java EE-related modules, including JAXB, had been deprecated and removed starting from JDK 9.
This blog may help.
https://jaxenter.com/jdk-11-java-ee-modules-140674.html

**Comment by pauljamescleary** [comment]
@exoego goodness, thanks for that article.  That is kind of insane that they did that

**Comment by pauljamescleary** [comment]
Looks like travis is having problems.  Version conflict in jaxb?

**Comment by exoego** [comment]
Thank you.
I will open PR for that.

**Comment by pauljamescleary** [comment]
`;validate;verify` worked for me on my local

**Pull request merged**
